name: CI Checks

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  spell-check:
    runs-on: ubuntu-latest
    steps:
      - name: Clone This Repo
        uses: actions/checkout@v2
      - name: Run spellings check
        uses: Skptak/CI-CD-Github-Actions/rust-spell-check@main
        with:
          path: ./
  rust-spell-check:
    runs-on: ubuntu-latest
    steps:
      - name: Clone This Repo
        uses: actions/checkout@v2
      - name: Run spellings check
        uses: Skptak/CI-CD-Github-Actions/rust-spell-check@rustSpellCheck
        with:
          path: ./
          lexicon: ./lexicon.txt
